// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Weaning605Interbeef_main
int Weaning605Interbeef_main(std::string paramFileName);
RcppExport SEXP _Weaning605Interbeef_Weaning605Interbeef_main(SEXP paramFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type paramFileName(paramFileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(Weaning605Interbeef_main(paramFileName));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Weaning605Interbeef_Weaning605Interbeef_main", (DL_FUNC) &_Weaning605Interbeef_Weaning605Interbeef_main, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Weaning605Interbeef(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
